In [18]:
#Environment build-up
env = [{0: ( 10, True ), 1: (  5, False), 2: (-10, False), 3: (-10, False), 4: (-10, False), 
        5: (-10, False), 6: (-10, False), 7: (-10, False), 8: (-10, False), 9: (-10, False)},
       {0: (-10, False), 1: ( 10, True ), 2: (  5, False), 3: (-10, False), 4: (-10, False), 
        5: (-10, False), 6: (-10, False), 7: (-10, False), 8: (-10, False), 9: (-10, False)},
       {0: (-10, False), 1: (-10, False), 2: ( 10, True ), 3: (  5, False), 4: (-10, False), 
        5: (-10, False), 6: (-10, False), 7: (-10, False), 8: (-10, False), 9: (-10, False)},
       {0: (-10, False), 1: (-10, False), 2: (-10, False), 3: ( 10, True ), 4: (  5, False), 
        5: (-10, False), 6: (-10, False), 7: (-10, False), 8: (-10, False), 9: (-10, False)},
       {0: (-10, False), 1: (-10, False), 2: (-10, False), 3: (-10, False), 4: ( 10, True ),
        5: (  5, False), 6: (-10, False), 7: (-10, False), 8: (-10, False), 9: (-10, False)},
       {0: (-10, False), 1: (-10, False), 2: (-10, False), 3: (-10, False), 4: (-10, False), 
        5: ( 10, True ), 6: (  5, False), 7: (-10, False), 8: (-10, False), 9: (-10, False)},
       {0: (-10, False), 1: (-10, False), 2: (-10, False), 3: (-10, False), 4: (-10, False),
        5: (-10, False), 6: ( 10, True ), 7: (  5, False), 8: (-10, False), 9: (-10, False)},
       {0: (-10, False), 1: (-10, False), 2: (-10, False), 3: (-10, False), 4: (-10, False),
        5: (-10, False), 6: (-10, False), 7: ( 10, True ), 8: (  5, False), 9: (-10, False)},
       {0: (-10, False), 1: (-10, False), 2: (-10, False), 3: (-10, False), 4: (-10, False),
        5: (-10, False), 6: (-10, False), 7: (-10, False), 8: ( 10, True ), 9: (  5, False)},
       {0: (  5, False), 1: (-10, False), 2: (-10, False), 3: (-10, False), 4: (-10, False),
        5: (-10, False), 6: (-10, False), 7: (-10, False), 8: (-10, False), 9: ( 10, True )}
      ]

In [20]:
print( env[1][0] )

(-10, False)


In [21]:
#Importing libraries
import numpy as np
import random
from IPython.display import clear_output

In [22]:
#Checking search table
q_table = np.zeros([10, 10])
print(q_table)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [23]:
# Parameters to compound how important is each test during the training phase
l_rate   = 0.25 # learning rate
w_import = 0.9 # how important it is for future rewards. Lower values, short term decisions. Higher, long-term 
r_select = 0.33 # aprox. 20% of actions will be randomly selected

for i in range(1, 10000000):
    r_state = random.randrange(0,9,1) # Rows of our environment (clients)
    r_ok = False
    
    while not r_ok:
        if random.uniform(0, 1) < r_select:
            r_act = random.randrange(0,10,1)     # Try randomly a path on the environment Columns (products)
        else:
            r_act = np.argmax(q_table[r_state]) # Selecting the best action based on learned values
        
        r_reward, r_ok = env[r_state][r_act] 
        
        o_measu = q_table[r_state, r_act]
        n_state = (r_state + 1 if r_state + 1 < 10 else 0) # Just using a valid range
        n_maxim = np.max(q_table[r_state])
        
        n_eval  = ((1 - l_rate) * o_measu) + (l_rate * (r_reward + w_import * n_maxim))
        q_table[r_state, r_act] = n_eval

        r_state = n_state
        
    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Training: {i}")

print("Training finished.\n")

Training: 9999900
Training finished.



In [24]:
#Checking search table
print(q_table)

[[100.  95.  80.  80.  80.  80.  80.  80.  80.  80.]
 [ 80. 100.  95.  80.  80.  80.  80.  80.  80.  80.]
 [ 80.  80. 100.  95.  80.  80.  80.  80.  80.  80.]
 [ 80.  80.  80. 100.  95.  80.  80.  80.  80.  80.]
 [ 80.  80.  80.  80. 100.  95.  80.  80.  80.  80.]
 [ 80.  80.  80.  80.  80. 100.  95.  80.  80.  80.]
 [ 80.  80.  80.  80.  80.  80. 100.  95.  80.  80.]
 [ 80.  80.  80.  80.  80.  80.  80. 100.  95.  80.]
 [ 80.  80.  80.  80.  80.  80.  80.  80. 100.  95.]
 [ 95.  80.  80.  80.  80.  80.  80.  80.  80. 100.]]


In [25]:
#Recommender testing
r_wrong   = 0
tentative = 17000

for _ in range(tentative):
    r_state = random.randrange(0,9,1)
    r_reward = 0    
    r_ok = False
    
    while not r_ok:
        r_act = np.argmax(q_table[r_state])
        r_reward, r_ok = env[r_state][r_act]

        if r_reward == -10:
            r_wrong += 1


print(f"I made {r_wrong} wrong suggestions after {tentative}.")

I made 0 wrong suggestions after 17000.
